In [11]:
#作业1：数组创建与属性分析

import numpy as np

# 创建 3x4 的二维数组
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# 1. 打印数组的形状、维度和数据类型
print("数组形状:", arr.shape)
print("数组维度:", arr.ndim)
print("数据类型:", arr.dtype)

# 2. 将数组元素乘以2并打印
arr_double = arr * 2
print("\n乘以2后的数组:")
print(arr_double)

# 3. 重塑为4x3的形状并打印
arr_reshaped = arr.reshape(4, 3)
print("\n重塑为4x3的数组:")
print(arr_reshaped)

数组形状: (3, 4)
数组维度: 2
数据类型: int32

乘以2后的数组:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

重塑为4x3的数组:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
#作业2：数组索引与切片

import numpy as np

# 给定数组
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

# 1. 提取第2行所有元素（索引为1）
row2 = array[1, :]
print("第2行元素:", row2)

# 2. 提取第3列所有元素（索引为2）
col3 = array[:, 2]
print("第3列元素:", col3)

# 3. 提取子数组（第1、2行和第2、3列）
sub_array = array[0:2, 1:3]
print("子数组:")
print(sub_array)

# 4. 将大于10的元素替换为0
array_modified = np.where(array > 10, 0, array)
print("\n修改后的数组:")
print(array_modified)

第2行元素: [5 6 7 8]
第3列元素: [ 3  7 11 15]
子数组:
[[2 3]
 [6 7]]

修改后的数组:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  0  0]
 [ 0  0  0  0]]


In [13]:
#作业3：数组运算与广播

import numpy as np

# 创建数组A（3x2）
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# 创建数组B（一维数组）
B = np.array([10, 20])

# 1. 计算A和B的逐元素相加（利用广播）
sum_result = A + B
print("A + B:")
print(sum_result)

# 2. 计算A和B的逐元素相乘（利用广播）
product_result = A * B
print("\nA * B:")
print(product_result)

# 3. 计算A的每一行与B的点积
dot_products = np.dot(A, B)
print("\nA的每一行与B的点积:")
print(dot_products)

A + B:
[[11 22]
 [13 24]
 [15 26]]

A * B:
[[ 10  40]
 [ 30  80]
 [ 50 120]]

A的每一行与B的点积:
[ 50 110 170]
